apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-container
spec:
  results:
    - description: Image digest
      name: IMAGE_DIGEST
    - description: Image repository where the built image was pushed
      name: IMAGE_URL
  params:
    - default: "quay.io/redhat-appstudio/sample-image"
      name: image-url
      description: Image URL
    - default: ""
      name: image-digest
      description: Image Digest (optional)
  steps:
    - image: quay.io/konflux-ci/konflux-test:latest
      script: |
        echo -n "$(params.image-url)" | tee $(results.IMAGE_URL.path)
        if [ -z "$(params.image-digest)" ]; then
          sha256=$(echo -n $RANDOM | sha256sum | head -c 64)
          echo -n "sha256:${sha256}" | tee $(results.IMAGE_DIGEST.path)
        else
          echo -n "$(params.image-digest)" | tee $(results.IMAGE_DIGEST.path)
        fi
