apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: clone-repository
spec:
  results:
    - description: The precise commit SHA that was fetched by this Task.
      name: commit
    - description: The precise URL that was fetched by this Task.
      name: url
  params:
    - default: "git@github.com:konflux-ci/integration-service.git"
      name: url
      description: Git URL
    - default: ""
      name: commit
      description: Commit SHA
  steps:
    - image: quay.io/konflux-ci/konflux-test:latest
      script: |
        echo "$(params.url)" | tee $(results.url.path)
        if [ -z "$(params.commit)" ]; then
          sha256=$(echo -n $RANDOM | sha256sum | head -c 64)
          echo -n "sha256:${sha256}" | tee $(results.commit.path)
        else
          echo -n "$(params.commit)" | tee $(results.commit.path)
        fi
