apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: test-output
spec:
  results:
    - name: TEST_OUTPUT
      description: Test output
  params:
    - default: "SUCCESS"
      name: RESULT
      description: Test result to be generated
  steps:
    - image: quay.io/konflux-ci/konflux-test:latest
      script: |
        TEST_OUTPUT=$(jq -rc --arg date $(date -u --iso-8601=seconds) --arg RESULT $(params.RESULT) --null-input \
          '{result: $RESULT, timestamp: $date, failures: 0, successes: 0, warnings: 0}')
        echo -n "${TEST_OUTPUT}" | tee $(results.TEST_OUTPUT.path)